services:
  mariadb:
    build:    
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:10.5.29 
    container_name: mariadb    
    restart: unless-stopped
    secrets:
      - db_admin_password
      - db_name
      - db_user
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(cat /run/secrets/db_admin_password)"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
  wordpress:
    build:    
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:6.8
    container_name: wordpress    
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    expose:
      - "9000"
    environment:  
      - WORDPRESS_ADMIN_EMAIL=liv@ldei-sva.42.fr
      - WORDPRESS_NORMAL_EMAIL=bot@ldei-sva.42.fr
      - WORDPRESS_TITLE=Il blog sui cavalli di ldei-sva
      - WORDPRESS_URL=https://ldei-sva.42.fr
      - DOMAIN_NAME=ldei-sva.42.fr
    secrets:
      - db_host
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_normal_user
      - wp_normal_password
  nginx:
    build:    
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:1.18.0
    container_name: nginx    
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - wp_network
    volumes:
      #- nginx_ssl:/etc/nginx/ssl
      - wordpress_data:/var/www/html
    environment:
      - DOMAIN_NAME=ldei-sva.42.fr
networks:
  wp_network:
    driver: bridge
    name: wordpress_network
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ldei-sva/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ldei-sva/data/wordpress
secrets:
  db_host:
    file: ../secrets/db_host.txt
  db_admin_password:
    file: ../secrets/db_admin_password.txt
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_normal_user:
    file: ../secrets/wp_normal_user.txt
  wp_normal_password:
    file: ../secrets/wp_normal_password.txt